name: Go

on:
  push:
    branches: [ master, release-0.2 ]
  pull_request:
    branches: [ master, release-0.2 ]

env:
  GO111MODULE: on
  GOLANGCI_LINT_VERSION: 1.42.1

jobs:
  test:
    strategy:
      matrix:
        go-versions: [1.15.x, 1.16.x, 1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    - uses: actions/cache@v1
      with:
        path: ~/.build/go-cache
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
    - name: go env
      run: go env
    - name: Fetch dependencies
      run: go get
    - name: Run tests
      run: go test ./...
    - name: Build
      run: go build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
      - uses: actions/cache@v1
        with:
          path: ~/.build/go-cache
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-
      - uses: actions/cache@v1
        id: bin
        with:
          path: ~/bin/
          key: golangi-lint-${{ env.GOLANGCI_LINT_VERSION }}
      - name: Install golangci-lint
        if: steps.bin.outputs.cache-hit != 'true'
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/bin/ v${GOLANGCI_LINT_VERSION}
      - name: Precompile packages
        run: go build ./...
      - name: Lint
        run: ~/bin/golangci-lint run --disable-all -v -E govet -E misspell -E gofmt -E ineffassign -E golint
